version: '3'
services:
  terraform:
    container_name: terraform
    build:
      context: ./.dockerfile/terraform
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    env_file:
      - ./.env
    tty: true