version: '3'
services:
  deploy:
    container_name: deploy
    build:
      context: ./dockerfile
      dockerfile: terraform
    volumes:
      - type: bind
        source: ./src
        target: /workspace
    env_file:
      - .env
    tty: true